services:
  telegram-scheduler:
    build: .
    container_name: telegram-scheduler
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./session:/app/session
    environment:
      - TZ=UTC  # Set your preferred timezone here
    stdin_open: true   # Keep STDIN open for interactive authentication
    tty: true          # Allocate a pseudo-TTY for interactive authentication 